### ISSUE TITLE
Any way to handle daylight savings?

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/terraform-aws-ecs-scheduled-task#3]
@JonRoma Could we maybe set up a lambda function to automatically switch a cron job from CST to CDT? Might not be worth the effort but I see @dimpsey doing things like this in his code:

```
# cst (winter) = 9:08pm,1:08am,5:08am,9:08am,1:08pm,5:08pm
# cdt (summer) = 10:08pm,2:08am,6:08am,10:08am,2:08pm,6:08pm
schedule_expression = "cron(8 3,7,11,15,19,23 * * ? *)"
```

This seems like a lot of unnecessary manual work. Would be great if we could have something like this:

```
# cst (winter) = 9:08pm,1:08am,5:08am,9:08am,1:08pm,5:08pm
# cdt (summer) = 10:08pm,2:08am,6:08am,10:08am,2:08pm,6:08pm
schedule_expression_cst = "cron(8 3,7,11,15,19,23 * * ? *)"
```

Then have lambda adjust the times automatically to adjust for daylight savings time. Thoughts?

**Comment by JonRoma** [comment]
It seems that most of our use cases involve tasks that should be run on a relatively consistent frequency, rather than at precise times. Fussing with this seems unnecessary, and the calculation between UTC and CST/CDT is straightforward, and only needs being made once.

Furthermore, there is a [bill in the Illinois General Assembly](https://www.illinoispolicy.org/illinois-senate-passes-bill-to-end-clock-change-during-daylight-saving-time/) to move to daylight time year round. If this passes, the conversion is moot.

My inclination is to close this as _wontfix_.

**Comment by ddriddle** [comment]
@JonRoma I tend to agree with you but if our customers have to make manual changes twice a year to deal with this then it would be better to automate the process. @dimpsey do your cron jobs really need to care about day light savings time?

**Comment by dimpsey** [comment]
I set up my cron processes that only one may need to adhere to a strict time.  That is the load-final-exams process which the Registrar wants to run at 9:30 AM every morning.  However, I have spoken with them and they so far flexible that it can be bumped up to 10:30 AM for CDT, which it is running at right now.  So far no issues, so I do think this is a non-issue at the moment.

Jeff

**Comment by JonRoma** [comment]
This seems worth closing at this point.
